### ISSUE TITLE
How to enable coverage option --coverage flag?

### ISSUE THREAD

**Issue by rafaellucio** [tuchk4/react-app-env#5]
Hi, I use this module in my workspace, but I can use --coverage flag, bug don't work, how do I aneble this?

Version module: "react-app-env": "^1.2.3"

Command Npm scripts

`"test:ci": "CI=true react-app-env --env-file=.env.test test --coverage"`

Or

`"test:ci": "CI=true react-app-env --env-file=.env.test test -- --coverage"`

Thanks

**Comment by tuchk4** [comment]
Sorry for long reposne
for some reason I lost this issue and PR :(

will publish new version tomorrow morning
